version: '3'
services:
  web:
    image: mydocker/apache:1.0.0.curso
    ports:
      - 80:80
    volumes:
     - /home/mariano/curso_docker/volume/web:/var/www/html
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - SERVICE_PORTS=80
      - LANG=es_AR.utf8
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 128m 
  mysqldb:
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306    
    volumes:
      - /home/mariano/curso_docker/volume/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
